<div class="col-md-12">
	<h1>Adicionar Post</h1>
	<div class="col-md-6 form-register">
		<form method="POST" action="/admin/postcreate">
			<div class="form-group">
			    <label for="name">Titulo</label>
			    <input type="text" name="titulo" class="form-control" id="titulo" placeholder="Digite o titulo do post">
			</div>
			<div class="form-group">
			    <label for="email">Conteudo</label>
			    <textarea class="form-control" name="texto" placeholder="Digite o conteúdo do post"></textarea>
			</div>
			<input type="hidden" name="id_usuario" value="<?php echo $this->userId; ?>">
			<button type="submit" class="btn btn-default">Adicionar</button>
		</form>
	</div>
</div>
