<div class="col-md-12">
	<h1>Adicionar Membro</h1>
	<div class="col-md-6 form-register">
		<form method="POST" action="/user/add/post">
			<div class="form-group">
			    <label for="name">Nome</label>
			    <input type="name" name="name" class="form-control" id="name" placeholder="Digite seu nome">
			</div>
			<div class="form-group">
			    <label for="email">E-mail</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail">
			</div>
			<div class="form-group">
			    <label for="nivel">Nível Hierárquico</label>
			    <select class="form-control">
			    	<option></option>
			    	<option value="0">Usuário</option>
			    	<option value="1">Membro</option>
			    	<option value="2">Criador de Conteúdo</option>
			    	<option value="3">Administrador</option>
			    </select>
			</div>
			<div class="form-group">
			    <label for="password">Senha</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha">
			</div>
			<div class="form-group">
			    <label for="confirmpassword">Confirme a senha</label>
			    <input type="password" name="confirmpassword" class="form-control" id="confirmpassword" placeholder="Confirme sua senha">
			</div>
			<button type="submit" class="btn btn-default">Adicionar</button>
		</form>
	</div>
</div>
