<h1>Editar Membro</h1>
<div class="col-md-6 form-register">
	<form method="POST" action="user/register">
		<div class="form-group">
		    <label for="name">Name</label>
		    <input type="name" name="name" class="form-control" id="name" placeholder="Digite seu nome">
		</div>
		<div class="form-group">
		    <label for="email">Email address</label>
		    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail">
		</div>
		<div class="form-group">
		    <label for="password">Password</label>
		    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha">
		</div>
		<div class="form-group">
		    <label for="confirmpassword">Confirm Password</label>
		    <input type="password" name="confirmpassword" class="form-control" id="confirmpassword" placeholder="Confirme sua senha">
		</div>
		<button type="submit" class="btn btn-default">Salvar</button>
	</form>
</div>