<?php 
	$userInfo = $this->userInfo;
 ?>

<h1>Editar Membro</h1>
<div class="col-md-6 form-register">
	<form method="POST" action="/user/edit/post">
		<input type="hidden" name="id" value="<?php echo $userInfo['id']; ?>">
		<div class="form-group">
		    <label for="name">Name</label>
		    <input type="name" name="name" class="form-control" id="name" placeholder="Digite seu nome" value="<?php echo $userInfo['nome']; ?>">
		</div>
		<div class="form-group">
		    <label for="email">Email address</label>
		    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail" value="<?php echo $userInfo['email']; ?>">
		</div>
		<div class="form-group">
			    <label for="nivel">Nível Hierárquico</label>
			    <select name="nivel" class="form-control" id="nivel">
			    	<option></option>
			    	<option value="0" <?php echo ($userInfo['nivel'] == 0) ? 'selected' : '' ?>>Usuário</option>
			    	<option value="1" <?php echo ($userInfo['nivel'] == 1) ? 'selected' : '' ?>>Membro</option>
			    	<option value="2" <?php echo ($userInfo['nivel'] == 2) ? 'selected' : '' ?>>Criador de Conteúdo</option>
			    	<option value="3" <?php echo ($userInfo['nivel'] == 3) ? 'selected' : '' ?>>Administrador</option> 
			    </select>
			</div>
		<div class="form-group">
		    <label for="password">Password</label>
		    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha" value="<?php echo $userInfo['senha']; ?>">
		</div>
		<div class="form-group">
		    <label for="confirmpassword">Confirm Password</label>
		    <input type="password" name="confirmpassword" class="form-control" id="confirmpassword" placeholder="Confirme sua senha" value="<?php echo $userInfo['senha']; ?>">
		</div>
		<button type="submit" class="btn btn-default">Salvar</button>
	</form>
</div>