<div class="col-md-12">
	<h1>Editar Post</h1>
	<div class="col-md-6 form-register">
		<form method="POST" action="/admin/postupdate">
			<input type="hidden" name="post_id" value="<?php echo $this->postInfo['id']; ?>">
			<div class="form-group">
			    <label for="name">Titulo</label>
			    <input type="text" name="titulo" class="form-control" id="titulo" placeholder="Digite o titulo do post" value="<?php echo $this->postInfo['titulo'] ?>">
			</div>
			<div class="form-group">
			    <label for="email">Conteúdo</label>
			    <textarea class="form-control" name="texto" placeholder="Digite o conteúdo do post"><?php echo $this->postInfo['texto'] ?></textarea>
			</div>
			<button type="submit" class="btn btn-default">Editar</button>
		</form>
	</div>
</div>
