<div class="col-md-12 form-login-register">
	<h1 class="page-title">Área administrativa</h1>
	<div class="col-md-6 form-login">
		<form method="POST" action="user/login">
			<div class="form-group">
			    <label for="email">Email address</label>
			    <input type="email" name="email" class="form-control" id="email" placeholder="Digite seu e-mail">
			</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" name="password" class="form-control" id="password" placeholder="Digite sua senha">
			</div>
			<button type="submit" class="btn btn-default">Entrar</button>
		</form>
	</div>
</div>