<div class="col-md-12">
	<h1>Gerenciar Equipe</h1>
	<a href="/admin/team/adduser" class="btn btn-default">Adicionar Membro</a>
	<h3>Lista de Membros</h3>
	<ul>
		<li>Membro 1 <a class="btn btn-default" href="/admin/edituser">Editar</a> <a class="btn btn-danger" href="/admin/deleteuser">Deletar</a></li>
		<li>Membro 2 <a class="btn btn-default" href="/admin/edituser">Editar</a> <a class="btn btn-danger" href="/admin/deleteuser">Deletar</a></li>
	</ul>
</div>
