<div class="col-md-12">
	<h1>Gerenciar Equipe</h1>
	<a href="/admin/team/adduser" class="btn btn-default">Adicionar Membro</a>
	<h3>Lista de Membros</h3>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome:</th>
				<th>E-mail</th>
				<th>Nivel</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->users as $user): ?>
				<tr>
					<td><?php echo $user['id']; ?></td>
					<td><?php echo $user['nome']; ?></td>
					<td><?php echo $user['email']; ?></td>
					<td><?php echo $user['nivel']; ?></td>
					<td><a class="btn btn-default" href="/user/edituser?id=<?php echo $user['id']; ?>">Editar</a> <a class="btn btn-danger" href="/user/deleteuser?id=<?php echo $user['id']; ?>">Deletar</a></td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>
