<div class="col-md-12">
	<h1 class="main-title">Bem vindo ao mini blog!</h1>
	<h3>Nós temos hoje <?php echo $this->postsCount; ?> postagens!</h3>
	<p>Estes são os últimos posts, selecione a que deseja ler:</p>

	<?php foreach($this->lastPosts as $post): ?>
	<div class="jumbotron post-container">
		<h1><?php echo $post['titulo']; ?></h1>
		<p><?php echo substr($post['texto'], 0, 20); ?></p>
		<p><a class="btn-default" href="/post/view?id=<?php echo $post['id']; ?>" role="button">Leia mais</a></p>
	</div>
	<?php endforeach; ?>

</div>

